// Define all map labels organized by category
export const mapLabels = {
  landmarks: [
    // Add landmark labels here
    // Valinor Island Landmarks

    // Krythan Island Landmarks
    {
      name: "Valley of the Dead",
      fontSize: 30,
      region: "Krythan",
      details: {
        title: "Valley of the Dead",
        coordinates: { x: 1373, y: 1434 },
        image: "",
        lore: "More information about Valley of the Dead is coming soon.",
        information: "",
        bonus: "",
        npcs: [],
        links: [],
      },
    },

    // Mainlands Landmarks

    // Darkwoods Region Landmarks

    // Battle Plains Region Landmarks
    {
      name: "Proudblood Valley",
      fontSize: 30,
      region: "Battle Plains",
      details: {
        title: "Proudblood Valley",
        coordinates: { x: 1751, y: 3403 },
        image: "",
        lore: "More information about Proudblood Valley is coming soon.",
        information: "",
        bonus: "",
        npcs: [],
        links: [],
      },
    },

    // Black Swamp Region Landmarks

    // Highlands Region Landmarks
    {
      name: "Death Tyrant Valley",
      fontSize: 35,
      region: "Highlands",
      details: {
        title: "Death Tyrant Valley",
        coordinates: { x: 3596, y: 2452 },
        image: "",
        lore: "More information about Death Tyrant Valley is coming soon.",
        information: "",
        bonus: "",
        npcs: [],
        links: [],
      },
    },
    {
      name: "Resource Valley",
      fontSize: 35,
      region: "Highlands",
      details: {
        title: "Resource Valley",
        coordinates: { x: 3411, y: 3258 },
        image: "",
        lore: "More information about Resource Valley is coming soon.",
        information: "",
        bonus: "",
        npcs: [],
        links: [],
      },
    },
    {
      name: "Rock Troll Coast",
      fontSize: 30,
      region: "Highlands",
      details: {
        title: "Rock Troll Coast",
        coordinates: { x: 3745, y: 3503 },
        image: "",
        lore: "More information about Rock Troll Coast is coming soon.",
        information: "",
        bonus: "",
        npcs: [],
        links: [],
      },
    },
    {
      name: "Valley of Giants",
      fontSize: 35,
      region: "Valley of Giants",
      details: {
        title: "Valley of Giants",
        coordinates: { x: 3066, y: 2942 },
        image: "",
        lore: "More information about Valley of Giants is coming soon.",
        information: "",
        bonus: "",
        npcs: [],
        links: [],
      },
    },

    // Badlands Region Landmarks
    {
      name: "Badlands",
      fontSize: 35,
      region: "Badlands",
      details: {
        title: "Badlands",
        coordinates: { x: 2785, y: 2764 },
        image: "",
        lore: "More information about Badlands is coming soon.",
        information: "",
        bonus: "",
        npcs: [],
        links: [],
      },
    },

    // Heartwood Coast Region Landmarks

    // Tundria Region Landmarks

    // Breakwater Region Landmarks

    // Western Isles Region Landmarks

    // Broken Finger Region Landmarks
  ],
  cities: [
    /* Valinor Island Cities */
    // Valinor Region Cities
    {
      name: "Valinor",
      fontSize: 24,
      region: "Valinor",
      details: {
        title: "Valinor",
        coordinates: { x: 758, y: 64 },
        image: "images/Valinor_Island-600x.png",
        lore: "Valinor is the starting city for new players, providing essential services and introductory quests to help them begin their journey in the world of Ashen Empires.",
        information: "",
        bonus: "",
        npcs: [
          {
            name: "Larodeth Lywelyn's Pub",
            info: "A place to rest and get quests.",
          },
          {
            name: "Micheal Vonda's Weapon Shop",
            info: "Sells starter weapons.",
          },
          {
            name: "Thomas Blackstone's Armor Shop",
            info: "Sells starter armor.",
          },
          { name: "Bank", info: "Securely store your items." },
        ],
        links: [{ text: "More info on Ashen Empires Wiki", url: "https://ashenempires.fandom.com/wiki/Valinor_Quests" }],
      },
    },

    // Non-Expansion Cities
    // Krythan Region Cities
    {
      name: "Jeel",
      fontSize: 30,
      region: "Krythan",
      details: {
        title: "Jeel",
        coordinates: { x: 289, y: 806 },
        image: "",
        lore: "More information about Jeel is coming soon.",
        information: "",
        bonus: "",
        npcs: [],
        links: [{ text: "Ashen Empires Wiki (Non-Expansion Quests)", url: "https://ashenempires.fandom.com/wiki/Non-Expansion_Quests#Jeel" }],
      },
    },
    {
      name: "Hothbra",
      fontSize: 30,
      region: "Krythan",
      details: {
        title: "Hothbra",
        coordinates: { x: 521, y: 1057 },
        image: "",
        lore: "More information about Hothbra is coming soon.",
        information: "",
        bonus: "",
        npcs: [],
        links: [{ text: "Ashen Empires Wiki (Non-Expansion Quests)", url: "https://ashenempires.fandom.com/wiki/Non-Expansion_Quests#Hothbra" }],
      },
    },
    {
      name: "Varg",
      fontSize: 30,
      region: "Krythan",
      details: {
        title: "Varg",
        coordinates: { x: 787, y: 1170 },
        image: "",
        lore: "More information about Varg is coming soon.",
        information: "",
        bonus: "",
        npcs: [],
        links: [{ text: "Ashen Empires Wiki (Non-Expansion Quests)", url: "https://ashenempires.fandom.com/wiki/Non-Expansion_Quests#Varg" }],
      },
    },
    {
      name: "New Korelth",
      fontSize: 30,
      region: "Krythan",
      details: {
        title: "New Korelth",
        coordinates: { x: 341, y: 1439 },
        image: "",
        lore: "<p>Once a vital travel nexus for the kingdom, the town of New Korelth has fallen. It now stands as the primary bastion and operational headquarters for the demonic Talazarian faction. Its original identity has been annihilated, its spirit conquered and corrupted to serve the forces of the fallen hero, Talazar. For loyal followers of King Lotor II, this is hostile and occupied territory.</p><p>The town's fate is steeped in tragic irony. In a bygone era, the mines near New Korelth housed the Shrine of Talazar, a monument built to honor his heroic deeds before his corruption. Now, the very land that once held his honor sacred has been desecrated, serving as the command center for his campaign of terror. The fall of New Korelth is the physical manifestation of the fall of Talazar himself—a brutal overwriting of his own noble legacy.</p><p>Today, the town's sole purpose is to advance the Talazarian war effort. Followers of the fallen hero are summoned here to speak with the Digmaster, who grants them access to the faction's high-level dungeon. This fortress, the heart of the corrupted town, bears a paradoxical name: the Ghost of Lotor. This name suggests that even in his demonic state, Talazar and his followers are haunted by the legacy—the \"ghost\"—of the king he betrayed, turning this bastion of power into a monument of his inescapable past.</p>",
        information: "",
        bonus: "",
        npcs: [],
        links: [],
      },
    },
    {
      name: "Vrethpool",
      fontSize: 30,
      region: "Krythan",
      details: {
        title: "Vrethpool",
        coordinates: { x: 669, y: 1669 },
        image: "",
        lore: "More information about Vrethpool is coming soon.",
        information: "",
        bonus: "",
        npcs: [],
        links: [{ text: "Ashen Empires Wiki (Non-Expansion Quests)", url: "https://ashenempires.fandom.com/wiki/Non-Expansion_Quests#Vrethpool" }],
      },
    },
    {
      name: "Lotor's Castle",
      fontSize: 30,
      region: "Silvest Valley",
      details: {
        title: "Lotor's Castle",
        coordinates: { x: 246, y: 1115 },
        image: "",
        lore: "More information about Lotor's Castle is coming soon.",
        information: "",
        bonus: "",
        npcs: [],
        links: [{ text: "Ashen Empires Wiki (Non-Expansion Quests)", url: "https://ashenempires.fandom.com/wiki/Non-Expansion_Quests#Lotor's_Castle" }],
      },
    },
    // Silvest Valley Region Cities
    {
      name: "Cliffside",
      fontSize: 30,
      region: "Silvest Valley",
      details: {
        title: "Cliffside",
        coordinates: { x: 1065, y: 1150 },
        image: "",
        lore: "More information about Cliffside is coming soon.",
        information: "",
        bonus: "",
        npcs: [],
        links: [{ text: "Ashen Empires Wiki (Non-Expansion Quests)", url: "https://ashenempires.fandom.com/wiki/Non-Expansion_Quests#Cliffside" }],
      },
    },
    {
      name: "Silvest",
      fontSize: 30,
      region: "Silvest Valley",
      details: {
        title: "Silvest",
        coordinates: { x: 1085, y: 1344 },
        image: "",
        lore: "More information about Silvest is coming soon.",
        information: "",
        bonus: "",
        npcs: [],
        links: [{ text: "Ashen Empires Wiki (Non-Expansion Quests)", url: "https://ashenempires.fandom.com/wiki/Non-Expansion_Quests#Silvest" }],
      },
    },
    {
      name: "Fort Eastwatch",
      fontSize: 30,
      region: "Silvest Valley",
      details: {
        title: "Fort Eastwatch",
        coordinates: { x: 1343, y: 1281 },
        image: "",
        lore: "More information about Fort Eastwatch is coming soon.",
        information: "",
        bonus: "",
        npcs: [],
        links: [{ text: "Ashen Empires Wiki (Non-Expansion Quests)", url: "https://ashenempires.fandom.com/wiki/Non-Expansion_Quests#Fort_Eastwatch" }],
      },
    },
    // Mainland Cities

    // Darkwoods Region Cities
    {
      name: "Redwake",
      fontSize: 30,
      region: "Darkwoods",
      details: {
        title: "Redwake",
        coordinates: { x: 455, y: 2824 },
        image: "",
        lore: "More information about Redwake is coming soon.",
        information: "",
        bonus: "",
        npcs: [],
        links: [{ text: "Ashen Empires Wiki (Non-Expansion Quests)", url: "https://ashenempires.fandom.com/wiki/Non-Expansion_Quests#Redwake" }],
      },
    },
    {
      name: "Whisperdale",
      fontSize: 30,
      region: "Darkwoods",
      details: {
        title: "Whisperdale",
        coordinates: { x: 404, y: 3417 },
        image: "",
        lore: "More information about Whisperdale is coming soon.",
        information: "",
        bonus: "",
        npcs: [],
        links: [{ text: "Ashen Empires Wiki (Non-Expansion Quests)", url: "https://ashenempires.fandom.com/wiki/Non-Expansion_Quests#Whisperdale" }],
      },
    },
    {
      name: "Autumn",
      fontSize: 30,
      region: "Darkwoods",
      details: {
        title: "Autumn",
        coordinates: { x: 591, y: 3388 },
        image: "",
        lore: "More information about Autumn is coming soon.",
        information: "",
        bonus: "",
        npcs: [],
        links: [{ text: "Ashen Empires Wiki (Non-Expansion Quests)", url: "https://ashenempires.fandom.com/wiki/Non-Expansion_Quests#Autumn" }],
      },
    },
    {
      name: "Darkfell",
      fontSize: 30,
      region: "Darkwoods",
      details: {
        title: "Darkfell",
        coordinates: { x: 900, y: 3063 },
        image: "",
        lore: "More information about Darkfell is coming soon.",
        information: "",
        bonus: "",
        npcs: [],
        links: [{ text: "Ashen Empires Wiki (Non-Expansion Quests)", url: "https://ashenempires.fandom.com/wiki/Non-Expansion_Quests#Darkfell" }],
      },
    },
    {
      name: "Dunmarrow",
      fontSize: 30,
      region: "Darkwoods",
      details: {
        title: "Dunmarrow",
        coordinates: { x: 1383, y: 3150 },
        image: "",
        lore: "More information about Dunmarrow is coming soon.",
        information: "",
        bonus: "",
        npcs: [],
        links: [{ text: "Ashen Empires Wiki (Non-Expansion Quests)", url: "https://ashenempires.fandom.com/wiki/Non-Expansion_Quests#Dunmarrow" }],
      },
    },
    {
      name: "Josody",
      fontSize: 30,
      region: "Darkwoods",
      details: {
        title: "Josody",
        coordinates: { x: 1320, y: 2476 },
        image: "",
        lore: "More information about Josody is coming soon.",
        information: "",
        bonus: "",
        npcs: [],
        links: [{ text: "Ashen Empires Wiki (Non-Expansion Quests)", url: "https://ashenempires.fandom.com/wiki/Non-Expansion_Quests#Josody" }],
      },
    },
    {
      name: "Gulley",
      fontSize: 30,
      region: "Darkwoods",
      details: {
        title: "Gulley",
        coordinates: { x: 1107, y: 3672 },
        image: "",
        lore: "More information about Gulley is coming soon.",
        information: "",
        bonus: "",
        npcs: [],
        links: [{ text: "Ashen Empires Wiki (Non-Expansion Quests)", url: "https://ashenempires.fandom.com/wiki/Non-Expansion_Quests#Gulley" }],
      },
    },

    // Highlands Region Cities
    {
      name: "Grell",
      fontSize: 30,
      region: "Highlands",
      details: {
        title: "Grell",
        coordinates: { x: 3239, y: 3606 },
        image: "",
        lore: "More information about Grell is coming soon.",
        bonus: "City Bonus: +1.5 Stamina Regen, +3% Body",
        npcs: [],
        links: [{ text: "Ashen Empires Wiki (Non-Expansion Quests)", url: "https://ashenempires.fandom.com/wiki/Non-Expansion_Quests#Grell" }],
      },
    },
    {
      name: "Arda",
      fontSize: 30,
      region: "Highlands",
      details: {
        title: "Arda",
        coordinates: { x: 3400, y: 3443 },
        image: "",
        lore: "More information about Arda is coming soon.",
        bonus: "City Bonus: +6 pct Blunt, +5 Strength",
        npcs: [],
        links: [{ text: "Ashen Empires Wiki (Non-Expansion Quests)", url: "https://ashenempires.fandom.com/wiki/Non-Expansion_Quests#Arda" }],
      },
    },
    {
      name: "Parian",
      fontSize: 30,
      region: "Highlands",
      details: {
        title: "Parian",
        coordinates: { x: 3461, y: 2938 },
        image: "",
        lore: "More information about Parian is coming soon.",
        information: "",
        bonus: "",
        npcs: [],
        links: [{ text: "Ashen Empires Wiki (Non-Expansion Quests)", url: "https://ashenempires.fandom.com/wiki/Non-Expansion_Quests#Parian" }],
      },
    },
    {
      name: "Ethera Palace",
      fontSize: 30,
      region: "Highlands",
      details: {
        title: "Ethera Palace",
        coordinates: { x: 3535, y: 3642 },
        image: "",
        lore: "More information about Ethera Palace is coming soon.",
        bonus: "City Bonus: +7% Magic Missile, +5 Intelligence",
        npcs: [],
        links: [{ text: "Ashen Empires Wiki (Non-Expansion Quests)", url: "https://ashenempires.fandom.com/wiki/Non-Expansion_Quests#Ethera_Palace" }],
      },
    },
    {
      name: "Darushk",
      fontSize: 30,
      region: "Highlands",
      details: {
        title: "Darushk",
        coordinates: { x: 3745, y: 2710 },
        image: "",
        lore: "More information about Darushk is coming soon.",
        information: "",
        bonus: "",
        npcs: [],
        links: [{ text: "Ashen Empires Wiki (Non-Expansion Quests)", url: "https://ashenempires.fandom.com/wiki/Non-Expansion_Quests#Darushk" }],
      },
    },

    // Battle Plains Region Cities
    {
      name: "Desprail",
      fontSize: 30,
      region: "Battle Plains",
      details: {
        title: "Desprail",
        coordinates: { x: 2219, y: 3234 },
        image: "",
        lore: "More information about Desprail is coming soon.",
        information: "",
        bonus: "",
        npcs: [],
        links: [{ text: "Ashen Empires Wiki (Non-Expansion Quests)", url: "https://ashenempires.fandom.com/wiki/Non-Expansion_Quests#Desprail" }],
      },
    },
    {
      name: "Chlera",
      fontSize: 30,
      region: "Battle Plains",
      details: {
        title: "Chlera",
        coordinates: { x: 2402, y: 3547 },
        image: "",
        lore: "More information about Chlera is coming soon.",
        information: "",
        bonus: "",
        npcs: [],
        links: [{ text: "Ashen Empires Wiki (Non-Expansion Quests)", url: "https://ashenempires.fandom.com/wiki/Non-Expansion_Quests#Chlera" }],
      },
    },
    {
      name: "Chaos Island",
      fontSize: 24,
      region: "Battle Plains",
      details: {
        title: "Chaos Island",
        coordinates: { x: 1822, y: 3054 },
        image: "",
        lore: "More information about Chaos Island is coming soon.",
        information: "",
        bonus: "",
        npcs: [],
        links: [],
      },
    },

    // Black Swamp Region Cities
    {
      name: "Samad",
      fontSize: 30,
      region: "Black Swamp",
      details: {
        title: "Samad",
        coordinates: { x: 2635, y: 3496 },
        image: "",
        lore: "More information about Samad is coming soon.",
        information: "",
        bonus: "",
        npcs: [],
        links: [{ text: "Ashen Empires Wiki (Non-Expansion Quests)", url: "https://ashenempires.fandom.com/wiki/Non-Expansion_Quests#Samad" }],
      },
    },
    {
      name: "Dawat",
      fontSize: 30,
      region: "Black Swamp",
      details: {
        title: "Dawat",
        coordinates: { x: 3087, y: 3355 },
        image: "",
        lore: "More information about Dawat is coming soon.",
        information: "",
        bonus: "",
        npcs: [],
        links: [{ text: "Ashen Empires Wiki (Non-Expansion Quests)", url: "https://ashenempires.fandom.com/wiki/Non-Expansion_Quests#Dawat" }],
      },
    },
    {
      name: "Krog",
      fontSize: 35,
      region: "Black Swamp",
      details: {
        title: "Krog",
        coordinates: { x: 3075, y: 3717 },
        image: "",
        lore: "More information about Krog is coming soon.",
        information: "",
        bonus: "",
        npcs: [],
        links: [{ text: "Ashen Empires Wiki (Non-Expansion Quests)", url: "https://ashenempires.fandom.com/wiki/Non-Expansion_Quests#Krog" }],
      },
    },
    {
      name: "Maraket",
      fontSize: 30,
      region: "Black Swamp",
      details: {
        title: "Maraket",
        coordinates: { x: 3063, y: 3977 },
        image: "",
        lore: "More information about Maraket is coming soon.",
        information: "",
        bonus: "",
        npcs: [],
        links: [{ text: "Ashen Empires Wiki (Non-Expansion Quests)", url: "https://ashenempires.fandom.com/wiki/Non-Expansion_Quests#Maraket" }],
      },
    },


    

    // Region: Tundria
    {
      name: "Hammerfist",
      fontSize: 24,
      region: "Tundria",
      details: {
        title: "Hammerfist",
        coordinates: { x: 2792, y: 848 },
        image: "",
        lore: "More information about Hammerfist is coming soon.",
        information: "",
        bonus: "",
        npcs: [],
        links: [{ text: "Ashen Empires Wiki (Talazars Revenge Quests)", url: "https://ashenempires.fandom.com/wiki/Talazars_Revenge_Quests#Hammerfist" }],
      },
    },
    {
      name: "Duremar",
      fontSize: 24,
      region: "Tundria",
      details: {
        title: "Duremar",
        coordinates: { x: 3648, y: 929 },
        image: "",
        lore: "More information about Duremar is coming soon.",
        information: "",
        bonus: "",
        npcs: [],
        links: [{ text: "Ashen Empires Wiki (Talazars Revenge Quests)", url: "https://ashenempires.fandom.com/wiki/Talazars_Revenge_Quests#Duremar" }],
      },
    },
    {
      name: "Maroven",
      fontSize: 24,
      region: "Tundria",
      details: {
        title: "Maroven",
        coordinates: { x: 1942, y: 1240 },
        image: "",
        lore: "More information about Maroven is coming soon.",
        information: "",
        bonus: "",
        npcs: [],
        links: [{ text: "Ashen Empires Wiki (Talazars Revenge Quests)", url: "https://ashenempires.fandom.com/wiki/Talazars_Revenge_Quests#Maroven" }],
      },
    },
    {
      name: "Ringhaven Citadel",
      fontSize: 24,
      region: "Tundria",
      details: {
        title: "Ringhaven Citadel",
        coordinates: { x: 2197, y: 1205 },
        image: "",
        lore: "More information about Ringhaven Citadel is coming soon.",
        information: "",
        bonus: "",
        npcs: [],
        links: [{ text: "Ashen Empires Wiki (Non-Expansion Quests)", url: "https://ashenempires.fandom.com/wiki/Talazars_Revenge_Quests#Ringhaven_Citadel" }],
      },
    },
    {
      name: "Farstead Keep",
      fontSize: 24,
      region: "Tundria",
      details: {
        title: "Farstead Keep",
        coordinates: { x: 2821, y: 1253 },
        image: "",
        lore: "More information about Farstead Keep is coming soon.",
        information: "",
        bonus: "",
        npcs: [],
        links: [{ text: "Ashen Empires Wiki (Non-Expansion Quests)", url: "https://ashenempires.fandom.com/wiki/Talazars_Revenge_Quests_Quests#Farstead_Keep" }],
      },
    },

    // Region: Heartwood Coast
    {
      name: "Valmond",
      fontSize: 24,
      region: "Heartwood Coast",
      details: {
        title: "Valmond",
        coordinates: { x: 2625, y: 2105 },
        image: "",
        lore: "More information about Valmond is coming soon.",
        information: "",
        bonus: "",
        npcs: [],
        links: [{ text: "Ashen Empires Wiki (Non-Expansion Quests)", url: "https://ashenempires.fandom.com/wiki/Talazars_Revenge_Quests_Quests#Valmond" }],
      },
    },
    {
      name: "Teylan",
      fontSize: 24,
      region: "Heartwood Coast",
      details: {
        title: "Teylan",
        coordinates: { x: 2496, y: 1615 },
        image: "",
        lore: "More information about Teylan is coming soon.",
        information: "",
        bonus: "",
        npcs: [],
        links: [{ text: "Ashen Empires Wiki (Non-Expansion Quests)", url: "https://ashenempires.fandom.com/wiki/Talazars_Revenge_Quests_Quests#Teylan" }],
      },
    },
    {
      name: "Syldural",
      fontSize: 24,
      region: "Heartwood Coast",
      details: {
        title: "Syldural",
        coordinates: { x: 3276, y: 1636 },
        image: "",
        lore: "More information about Syldural is coming soon.",
        information: "",
        bonus: "",
        npcs: [],
        links: [{ text: "Ashen Empires Wiki (Non-Expansion Quests)", url: "https://ashenempires.fandom.com/wiki/Talazars_Revenge_Quests_Quests#Syldural" }],
      },
    },

    // Region: Sands of Creation
    {
      name: "Khafra",
      fontSize: 30,
      region: "Sands of Creation",
      details: {
        title: "Khafra",
        coordinates: { x: 247, y: 2743 },
        image: "",
        lore: "More information about Khafra is coming soon.",
        information: "",
        bonus: "",
        npcs: [],
        links: [{ text: "Ashen Empires Wiki (Non-Expansion Quests)", url: "https://ashenempires.fandom.com/wiki/Sands_of_Creation_Quests_Quests#Khafra" }],
      },
    },
    {
      name: "Ruhura",
      fontSize: 30,
      region: "Sands of Creation",
      details: {
        title: "Ruhura",
        coordinates: { x: 380, y: 3978 },
        image: "",
        lore: "More information about Ruhura is coming soon.",
        information: "",
        bonus: "",
        npcs: [],
        links: [{ text: "Ashen Empires Wiki (Non-Expansion Quests)", url: "https://ashenempires.fandom.com/wiki/Sands_of_Creation_Quests_Quests#Ruhura" }],
      },
    },

    // Region: Breakwater
    {
      name: "Roycroft",
      fontSize: 35,
      region: "Breakwater",
      details: {
        title: "Roycroft",
        coordinates: { x: 2447, y: 2335 },
        image: "",
        lore: "More information about Roycroft is coming soon.",
        information: "",
        bonus: "",
        npcs: [],
        links: [],
      },
    },
    {
      name: "New Town",
      fontSize: 35,
      region: "Breakwater",
      details: {
        title: "New Town",
        coordinates: { x: 1960, y: 1884 },
        image: "",
        lore: "More information about New Town is coming soon.",
        information: "",
        bonus: "",
        npcs: [],
        links: [],
      },
    },
    {
      name: "New Royale",
      fontSize: 35,
      region: "Breakwater",
      details: {
        title: "New Royale",
        coordinates: { x: 1392, y: 1897 },
        image: "",
        lore: "More information about New Royale is coming soon.",
        information: "",
        bonus: "",
        npcs: [],
        links: [],
      },
    },

    // Region: Broken Finger Cities
    {
      name: "Broken Finger Town",
      fontSize: 20,
      region: "Broken Finger",
      details: {
        title: "Broken Finger Town",
        coordinates: { x: 1152, y: 3711 },
        image: "",
        lore: "More information about Broken Finger Town is coming soon.",
        information: "",
        bonus: "",
        npcs: [],
        links: [],
      },
    },
  ],

  islands: [
    //Individual Islands 
    {
      name: "GM Island",
      fontSize: 30,
      region: "Special",
      details: {
        title: "GM Island",
        coordinates: { x: 149, y: 69 },
        image: "",
        lore: "More information about GM Island is coming soon.",
        information: "",
        bonus: "",
        npcs: [],
        links: [],
      },
    },
    {
      name: "Minotaur Island",
      fontSize: 30,
      region: "Western Isles",
      details: {
        title: "Minotaur Island",
        coordinates: { x: 136, y: 229 },
        image: "",
        lore: "More information about Minotaur Island is coming soon.",
        information: "",
        bonus: "",
        npcs: [],
        links: [],
      },
    },
    {
      name: "Party Island",
      fontSize: 30,
      region: "Western Isles",
      details: {
        title: "Party Island",
        coordinates: { x: 420, y: 68 },
        image: "images/Party_Island.png",
        lore: "A festive island known for celebrations. It holds the main portal to access Lotor's Summer Palace.",
        information: "",
        bonus: "",
        npcs: [
          { name: "Dalgo's Tavern", info: "A lively tavern on the island." },
          {
            name: "Portal to Lotor's Summer Palace",
            info: "The primary way to reach the palace.",
          },
        ],
        links: [],
      },
    },
    {
      name: "Lotor's Prison",
      fontSize: 30,
      region: "Western Isles",
      details: {
        title: "Lotor's Prison",
        coordinates: { x: 1544, y: 545 },
        image: "",
        lore: "More information about Lotor's Prison is coming soon.",
        information: "",
        bonus: "",
        npcs: [],
        links: [],
      },
    },
    {
      name: "Lotor's Summer Palace",
      fontSize: 30,
      region: "Western Isles",
      details: {
        title: "Lotor's Summer Palace",
        coordinates: { x: 774, y: 570 },
        image: "images/LSP.png",
        lore: "Lotor's Summer Palace is a central hub for players, offering access to various islands, housing realms, and a wide array of shops and services. It's a safe zone bustling with activity.",
        information: "",
        bonus: "",
        npcs: [
          {
            name: "Captain Renwood",
            info: "Offers quests to brave adventurers.",
          },
          { name: "Donkeo", info: "A mysterious figure with unique quests." },
          { name: "O'riles Weapon Shop", info: "Sells a variety of weapons." },
          {
            name: "Colleen Franks' Armor Shop",
            info: "Provides sturdy armor for all classes.",
          },
          {
            name: "Bank",
            info: "Securely store your valuable items and gold.",
          },
        ],
        links: [{ text: "More info on Ashen Empires Wiki", url: "#" }],
      },
    },
    {
      name: "Real Estate Island",
      fontSize: 30,
      region: "Western Isles",
      details: {
        title: "Real Estate Island",
        coordinates: { x: 662, y: 629 },
        image: "",
        lore: "More information about Real Estate Island is coming soon.",
        information: "",
        bonus: "",
        npcs: [],
        links: [],
      },
    },
    {
      name: "Guild Arena Island",
      fontSize: 30,
      region: "Western Isles",
      details: {
        title: "Guild Arena Island",
        coordinates: { x: 87, y: 941 },
        image: "",
        lore: "More information about Guild Arena Island is coming soon.",
        information: "",
        bonus: "",
        npcs: [],
        links: [],
      },
    },
    {
      name: "Valinor Island",
      fontSize: 35,
      region: "Valinor",
      details: {
        title: "Valinor Island",
        coordinates: { x: 939, y: 59 },
        image: "",
        lore: "More information about Valinor Island is coming soon.",
        information: "",
        bonus: "",
        npcs: [],
        links: [],
      },
    },
    {
      name: "Krythan Island",
      fontSize: 35,
      region: "Krythan Island",
      details: {
        title: "Krythan Island",
        coordinates: { x: 1089, y: 991 },
        image: "",
        lore: "More information about Krythan Island is coming soon.",
        information: "",
        bonus: "",
        npcs: [],
        links: [],
      },
    },
    // Western Isles Region
    
    // Werewolf Island Cities
    {
      name: "Lycanth",
      fontSize: 30,
      region: "Western Isles",
      details: {
        title: "Lycanth",
        coordinates: { x: 259, y: 2632 },
        image: "",
        lore: "More information about Lycanth is coming soon.",
        information: "",
        bonus: "",
        npcs: [],
        links: [],
      },
    },
    {
      name: "Monk Island",
      fontSize: 30,
      region: "Western Isles", // I think this is correct because of proximity to Krythan Island, but it could be Western Isles. Question Mark
      details: {
        title: "Monk Island",
        coordinates: { x: 560, y: 656 },
        image: "",
        lore: "More information about Monk Island is coming soon.",
        information: "",
        bonus: "",
        npcs: [],
        links: [],
      },
    },
    {
      name: "Lopal",
      fontSize: 30,
      region: "Western Isles",
      details: {
        title: "Lopal",
        coordinates: { x: 389, y: 2182 },
        image: "",
        lore: "More information about Lopal is coming soon.",
        information: "",
        bonus: "",
        npcs: [],
        links: [],
      },
    },
    {
      name: "Scorched Island",
      fontSize: 35,
      region: "Western Isles",
      details: {
        title: "Scorched Island",
        coordinates: { x: 794, y: 2091 },
        image: "",
        lore: "More information about Scorched Island is coming soon.",
        information: "",
        bonus: "",
        npcs: [],
        links: [],
      },
    },
    {
      name: "Hell",
      fontSize: 45,
      region: "Western Isles",
      details: {
        title: "Hell",
        coordinates: { x: 1129, y: 3194 },
        image: "",
        lore: "More information about Hell is coming soon.",
        information: "",
        bonus: "",
        npcs: [],
        links: [],
      },
    },
    
    {
      name: "Deserted Island",
      fontSize: 20,
      region: "Western Isles",
      details: {
        title: "Deserted Island",
        coordinates: { x: 222, y: 424 },
        image: "",
        lore: "More information about Deserted Island is coming soon.",
        information: "",
        bonus: "",
        npcs: [],
        links: [],
      },
    },
    {
      name: "Scarab Island",
      fontSize: 35,
      region: "Western Isles",
      details: {
        title: "Scarab Island",
        coordinates: { x: 258, y: 2047 },
        image: "",
        lore: "More information about Scarab Island is coming soon.",
        information: "",
        bonus: "",
        npcs: [],
        links: [],
      },
    },
    {
      name: "Werewolf Island",
      fontSize: 35,
      region: "Western Isles",
      details: {
        title: "Werewolf Island",
        coordinates: { x: 462, y: 2494 },
        image: "",
        lore: "More information about Werewolf Island is coming soon.",
        information: "",
        bonus: "",
        npcs: [],
        links: [],
      },
    },
    {
      name: "Dragoon Island",
      fontSize: 25,
      region: "Western Isles", // I think this is correct because of proximity to Darkwoods and the bridge, but it could be Western Isles. Question Mark
      details: {
        title: "Dragoon Island",
        coordinates: { x: 349, y: 3237 },
        image: "",
        lore: "More information about Dragoon Island is coming soon.",
        information: "",
        bonus: "",
        npcs: [],
        links: [],
      },
    },
    {
      name: "Obelisk Island",
      fontSize: 25,
      region: "Western Isles",
      details: {
        title: "Obelisk Island",
        coordinates: { x: 2116, y: 2703 },
        image: "",
        lore: "More information about Obelisk Island is coming soon.",
        information: "",
        bonus: "",
        npcs: [],
        links: [],
      },
    },
    {
      name: "Ettin Island",
      fontSize: 30,
      region: "Western Isles",
      details: {
        title: "Ettin Island",
        coordinates: { x: 1671, y: 1680 },
        image: "",
        lore: "More information about Ettin Island is coming soon.",
        information: "",
        bonus: "",
        npcs: [],
        links: [],
      },
    },
    
    {
      name: "PvP Island",
      fontSize: 30,
      region: "Western Isles",
      details: {
        title: "PvP Island",
        coordinates: { x: 3892, y: 1687 },
        image: "",
        lore: "More information about PvP Island is coming soon.",
        information: "",
        bonus: "",
        npcs: [],
        links: [],
      },
    },
    {
      name: "Greater Dragon Island",
      fontSize: 25,
      region: "Sands of Creation",
      details: {
        title: "Greater Dragon Island",
        coordinates: { x: 159, y: 3791 },
        image: "",
        lore: "More information about Greater Dragon Island is coming soon.",
        information: "",
        bonus: "",
        npcs: [],
        links: [],
      },
    },
    {
      name: "Northern Frost Giant Island",
      fontSize: 30,
      region: "Tundria",
      details: {
        title: "Northern Frost Giant Island",
        coordinates: { x: 3330, y: 253 },
        image: "",
        lore: "More information about Northern Frost Giant Island is coming soon.",
        information: "",
        bonus: "",
        npcs: [],
        links: [],
      },
    },
    {
      name: "Artonian Island",
      fontSize: 20,
      region: "Sands of Creation",
      details: {
        title: "Artonian Island",
        coordinates: { x: 247, y: 3375 },
        image: "",
        lore: "More information about Artonian Island is coming soon.",
        information: "",
        bonus: "",
        npcs: [],
        links: [],
      },
    },
    {
      name: "Vel Dran",
      fontSize: 24,
      region: "Highlands",
      details: {
        title: "Vel Dran",
        coordinates: { x: 3152, y: 3191 },
        image: "",
        lore: "More information about Vel Dran is coming soon.",
        information: "",
        bonus: "",
        npcs: [],
        links: [],
      },
    },
    
    {
      name: "Test Island",
      fontSize: 24,
      region: "Western Isles",
      details: {
        title: "Test Island",
        coordinates: { x: 3922, y: 3727 },
        image: "",
        lore: "More information about Test Island is coming soon.",
        information: "",
        bonus: "",
        npcs: [],
        links: [],
      },
    },
    {
      name: "Unnamed Island",
      fontSize: 30,
      region: "Tundria",
      details: {
        title: "Unnamed Island",
        coordinates: { x: 3798, y: 974 },
        image: "",
        lore: "More information about Unnamed Island is coming soon.",
        information: "",
        bonus: "",
        npcs: [],
        links: [],
      },
    },
    {
      name: "Crab Island",
      fontSize: 30,
      region: "Breakwater",
      details: {
        title: "Crab Island",
        coordinates: { x: 1062, y: 1950 },
        image: "",
        lore: "More information about Crab Island is coming soon.",
        information: "",
        bonus: "",
        npcs: [],
        links: [],
      },
    },

    // Sands of Creation Islands Technically might be Ruhura Island and Khafra Island, but this might be redundant.
  ],

  dungeons: [
    // Dungeons and Lairs Here

    // Krythan Island Dungeons - Region: Krythan
    //  
    {
      name: "Cultist Lair",
      fontSize: 20,
      region: "Krythan",
      details: {
        title: "Cultist Lair",
        coordinates: { x: 873, y: 1376 },
        image: "",
        lore: "More information about Cultist Lair is coming soon.",
        information: "",
        bonus: "",
        npcs: [],
        links: [],
      },
    },

    // Valinor Island Dungeons - Region: Valinor
    {
      name: "Bonesnarl's Lair",
      fontSize: 20,
      region: "Valinor",
      details: {
        title: "Bonesnarl's Lair",
        coordinates: { x: 865, y: 301 },
        image: "",
        lore: "More information about Bonesnarl's Lair is coming soon.",
        information: "",
        bonus: "",
        npcs: [],
        links: [],
      },
    },
  ],

  caves: [
    // Caves and Mines Here

    // Region: Valinor

    // Krythan Island Caves
    // Region: Krythan
    {
      name: "Minion Cave",
      fontSize: 20,
      region: "Krythan",
      details: {
        title: "Minion Cave",
        coordinates: { x: 503, y: 684 },
        image: "",
        lore: "More information about Minion Cave is coming soon.",
        information: "",
        bonus: "",
        npcs: [],
        links: [],
      },
    },
    {
      name: "Minion Cave",
      fontSize: 20,
      region: "Krythan",
      details: {
        title: "Minion Cave",
        coordinates: { x: 439, y: 760 },
        image: "",
        lore: "More information about Minion Cave is coming soon.",
        information: "",
        bonus: "",
        npcs: [],
        links: [],
      },
    },
    {
      name: "Flataga Mines",
      fontSize: 20,
      region: "Krythan",
      details: {
        title: "Flataga Mines",
        coordinates: { x: 390, y: 1317 },
        image: "",
        lore: "More information about Flataga Mines is coming soon.",
        information: "",
        bonus: "",
        npcs: [],
        links: [],
      },
    },
    // Region: Silvest Valley
    {
      name: "Silvest Mines",
      fontSize: 20,
      region: "Silvest Valley",
      details: {
        title: "Silvest Mines",
        coordinates: { x: 1016, y: 1108 },
        image: "",
        lore: "More information about Silvest Mines is coming soon.",
        information: "",
        bonus: "",
        npcs: [],
        links: [],
      },
    },
    {
      name: "Dalvon Mines",
      fontSize: 20,
      region: "Silvest Valley",
      details: {
        title: "Dalvon Mines",
        coordinates: { x: 1432, y: 1378 },
        image: "",
        lore: "More information about Dalvon Mines is coming soon.",
        information: "",
        bonus: "",
        npcs: [],
        links: [],
      },
    },
    {
      name: "Orc Cave",
      fontSize: 20,
      region: "Silvest Valley",
      details: {
        title: "Orc Cave",
        coordinates: { x: 1180, y: 1300 },
        image: "",
        lore: "More information about Orc Cave is coming soon.",
        information: "",
        bonus: "",
        npcs: [],
        links: [],
      },
    },
    

    /* Mainland Caves */

    // Region: Darkwoods Caves
    // Region: Battle Plains

    // Region: Black Swamp
    {
      name: "Ivogur's Mine",
      fontSize: 20,
      region: "Black Swamp",
      details: {
        title: "Ivogur's Mine",
        coordinates: { x: 2962, y: 3909 },
        image: "",
        lore: "More information about Ivogur's Mine is coming soon.",
        information: "",
        bonus: "",
        npcs: [],
        links: [],
      },
    },
    // Region: Valley of Giants

    // Heartwood Coast Caves

    // Tundria Caves

    // Breakwater Caves

    // Western Isles Caves

    // Broken Finger Caves
  ],

  interests: [
    // Places of Interest Here

    // Place of Interest - Region: Valinor
    {
      name: "Duncan's Cottage",
      fontSize: 20,
      region: "Valinor",
      details: {
        title: "Duncan's Cottage",
        coordinates: { x: 650, y: 173 },
        image: "",
        lore: "More information about Duncan's Cottage is coming soon.",
        information: "",
        bonus: "",
        npcs: [],
        links: [],
      },
    },
    {
      name: "Ruined Temple",
      fontSize: 20,
      region: "Valinor",
      details: {
        title: "Ruined Temple",
        coordinates: { x: 569, y: 312 },
        image: "",
        lore: "More information about Ruined Temple is coming soon.",
        information: "",
        bonus: "",
        npcs: [],
        links: [],
      },
    },
    {
      name: "Lanore",
      fontSize: 20,
      region: "Valinor",
      details: {
        title: "Lanore",
        coordinates: { x: 640, y: 361 },
        image: "",
        lore: "More information about Lanore is coming soon.",
        information: "",
        bonus: "",
        npcs: [],
        links: [],
      },
    },
    {
      name: "Ecclain's Caravan",
      fontSize: 20,
      region: "Valinor",
      details: {
        title: "Ecclain's Caravan",
        coordinates: { x: 1082, y: 467 },
        image: "",
        lore: "More information about Ecclain's Caravan is coming soon.",
        information: "",
        bonus: "",
        npcs: [],
        links: [],
      },
    },
    {
      name: "Valinor Ant Hill",
      fontSize: 20,
      region: "Valinor",
      details: {
        title: "Valinor Ant Hill",
        coordinates: { x: 1042, y: 281 },
        image: "",
        lore: "More information about Valinor Ant Hill is coming soon.",
        information: "",
        bonus: "",
        npcs: [],
        links: [],
      },
    },
    {
      name: "Hermit's Hut",
      fontSize: 20,
      region: "Valinor",
      details: {
        title: "Hermit's Hut",
        coordinates: { x: 964, y: 122 },
        image: "",
        lore: "More information about Hermit's Hut is coming soon.",
        information: "",
        bonus: "",
        npcs: [],
        links: [],
      },
    },

    // Places of Interest - Region: Krythan
    {
      name: "Gideon Cottage",
      fontSize: 20,
      region: "Krythan",
      details: {
        title: "Gideon Cottage",
        coordinates: { x: 508, y: 573 },
        image: "",
        lore: "More information about Gideon Cottage is coming soon.",
        information: "",
        bonus: "",
        npcs: [],
        links: [],
      },
    },
    {
      name: "Mirthik's Dwelling",
      fontSize: 20,
      region: "Krythan",
      details: {
        title: "Mirthik's Dwelling",
        coordinates: { x: 507, y: 639 },
        image: "",
        lore: "More information about Mirthik's Dwelling is coming soon.",
        information: "",
        bonus: "",
        npcs: [],
        links: [],
      },
    },
    {
      name: "Jeel Ruins",
      fontSize: 20,
      region: "Krythan",
      details: {
        title: "Jeel Ruins",
        coordinates: { x: 503, y: 752 },
        image: "",
        lore: "More information about Jeel Ruins is coming soon.",
        information: "",
        bonus: "",
        npcs: [],
        links: [],
      },
    },
    {
      name: "Crypt of Kargoth",
      fontSize: 20,
      region: "Krythan",
      details: {
        title: "Crypt of Kargoth",
        coordinates: { x: 435, y: 849 },
        image: "",
        lore: "More information about Crypt of Kargoth is coming soon.",
        information: "",
        bonus: "",
        npcs: [],
        links: [],
      },
    },
    {
      name: "Ruins of Tal S'kar",
      fontSize: 20,
      region: "Krythan",
      details: {
        title: "Ruins of Tal S'kar",
        coordinates: { x: 189, y: 988 },
        image: "",
        lore: "More information about Ruins of Tal S'kar is coming soon.",
        information: "",
        bonus: "",
        npcs: [],
        links: [],
      },
    },
    {
      name: "Holendar's Mansion",
      fontSize: 20,
      region: "Krythan",
      details: {
        title: "Holendar's Mansion",
        coordinates: { x: 831, y: 1034 },
        image: "",
        lore: "More information about Holendar's Mansion is coming soon.",
        information: "",
        bonus: "",
        npcs: [],
        links: [],
      },
    },
    {
      name: "Krythan Cemetary",
      fontSize: 20,
      region: "Krythan",
      details: {
        title: "Krythan Cemetary",
        coordinates: { x: 894, y: 1022 },
        image: "",
        lore: "More information about Krythan Cemetary is coming soon.",
        information: "",
        bonus: "",
        npcs: [],
        links: [],
      },
    },
    {
      name: "Scalo's Den",
      fontSize: 20,
      region: "Krythan",
      details: {
        title: "Scalo's Den",
        coordinates: { x: 835, y: 1278 },
        image: "",
        lore: "More information about Scalo's Den is coming soon.",
        information: "",
        bonus: "",
        npcs: [],
        links: [],
      },
    },
    {
      name: "Kobold Castle",
      fontSize: 18,
      region: "Krythan",
      details: {
        title: "Kobold Castle",
        coordinates: { x: 1278, y: 1122 },
        image: "",
        lore: "More information about Kobold Castle is coming soon.",
        information: "",
        bonus: "",
        npcs: [],
        links: [],
      },
    },
    {
      name: "Karzak Cove",
      fontSize: 20,
      region: "Krythan",
      details: {
        title: "Karzak Cove",
        coordinates: { x: 1375, y: 1076 },
        image: "",
        lore: "More information about Karzak Cove is coming soon.",
        information: "",
        bonus: "",
        npcs: [],
        links: [],
      },
    },
    {
      name: "Tallem'im house",
      fontSize: 20,
      region: "Krythan",
      details: {
        title: "Tallem'im house",
        coordinates: { x: 87, y: 1502 },
        image: "",
        lore: "More information about Tallem'im house is coming soon.",
        information: "",
        bonus: "",
        npcs: [],
        links: [],
      },
    },
    {
      name: "Wasp Hive",
      fontSize: 20,
      region: "Krythan",
      details: {
        title: "Wasp Hive",
        coordinates: { x: 515, y: 1301 },
        image: "",
        lore: "More information about Wasp Hive is coming soon.",
        information: "",
        bonus: "",
        npcs: [],
        links: [],
      },
    },
    {
      name: "Orc Fort",
      fontSize: 18,
      region: "Krythan",
      details: {
        title: "Orc Fort",
        coordinates: { x: 781, y: 1531 },
        image: "",
        lore: "More information about Orc Fort is coming soon.",
        information: "",
        bonus: "",
        npcs: [],
        links: [],
      },
    },

    // Places of Interest - Region: Western Isles 5022
    
    {
      name: "Minion's of Talazar's Stronghold",
      fontSize: 20,
      region: "Hell",
      details: {
        title: "Minion's of Talazar's Stronghold",
        coordinates: { x: 1199, y: 3340 },
        image: "",
        lore: "More information about Minion's of Talazar's Stronghold is coming soon.",
        information: "",
        bonus: "",
        npcs: [],
        links: [],
      },
    },

    /* Mainland Places of Interest */
    // Darkwoods Places of Interest
    {
      name: "Josody Theif Fort",
      fontSize: 18,
      region: "Darkwoods",
      details: {
        title: "Josody Theif Fort",
        coordinates: { x: 935, y: 2575 },
        image: "",
        lore: "More information about Josody Theif Fort is coming soon.",
        information: "",
        bonus: "",
        npcs: [],
        links: [],
      },
    },
    {
      name: "Crypt of Ryonkah",
      fontSize: 20,
      region: "Darkwoods",
      details: {
        title: "Crypt of Ryonkah",
        coordinates: { x: 1029, y: 2976 },
        image: "",
        lore: "More information about Crypt of Ryonkah is coming soon.",
        information: "",
        bonus: "",
        npcs: [],
        links: [],
      },
    },
    {
      name: "Lord Vezryl's Estate",
      fontSize: 20,
      region: "Darkwoods",
      details: {
        title: "Lord Vezryl's Estate",
        coordinates: { x: 554, y: 3157 },
        image: "",
        lore: "More information about Lord Vezryl's Estate is coming soon.",
        information: "",
        bonus: "",
        npcs: [],
        links: [],
      },
    },
    {
      name: "Burslord's Hunting Lodge",
      fontSize: 20,
      region: "Darkwoods",
      details: {
        title: "Burslord's Hunting Lodge",
        coordinates: { x: 682, y: 3388 },
        image: "",
        lore: "More information about Burslord's Hunting Lodge is coming soon.",
        information: "",
        bonus: "",
        npcs: [],
        links: [],
      },
    },
    {
      name: "Mnemmon",
      fontSize: 25,
      region: "Darkwoods",
      details: {
        title: "Mnemmon",
        coordinates: { x: 910, y: 3215 },
        image: "",
        lore: "More information about Mnemmon is coming soon.",
        information: "",
        bonus: "",
        npcs: [],
        links: [],
      },
    },
    {
      name: "Mnemmon Gaol",
      fontSize: 20,
      region: "Darkwoods",
      details: {
        title: "Mnemmon Gaol",
        coordinates: { x: 880, y: 3389 },
        image: "",
        lore: "More information about Mnemmon Gaol is coming soon.",
        information: "",
        bonus: "",
        npcs: [],
        links: [],
      },
    },
    {
      name: "Necropolis",
      fontSize: 20,
      region: "Necropolis",
      details: {
        title: "Necropolis",
        coordinates: { x: 1357, y: 2907 },
        image: "",
        lore: "More information about Necropolis is coming soon.",
        information: "",
        bonus: "",
        npcs: [],
        links: [],
      },
    },
    {
      name: "Astari Ruin Shelter",
      fontSize: 20,
      region: "Darkwoods",
      details: {
        title: "Astari Ruin Shelter",
        coordinates: { x: 814, y: 3222 },
        image: "",
        lore: "More information about Astari Ruin Shelter is coming soon.",
        information: "",
        bonus: "",
        npcs: [],
        links: [],
      },
    },
    {
      name: "Tuvok", // This is the name of the NPC who lives here.
      fontSize: 20,
      region: "Darkwoods", // I'm not sure if this is the Name of the place or the name of the NPC that lives there. Question Mark
      details: {
        title: "Tuvok",
        coordinates: { x: 1031, y: 2890 },
        image: "",
        lore: "More information about Tuvok is coming soon.",
        information: "",
        bonus: "",
        npcs: [],
        links: [],
      },
    },
    {
      name: "Warg Pen",
      fontSize: 20,
      region: "Darkwoods",
      details: {
        title: "Warg Pen",
        coordinates: { x: 1368, y: 2736 },
        image: "",
        lore: "More information about Warg Pen is coming soon.",
        information: "",
        bonus: "",
        npcs: [],
        links: [],
      },
    },
    {
      name: "Gadros Ruins",
      fontSize: 20,
      region: "Darkwoods",
      details: {
        title: "Gadros Ruins",
        coordinates: { x: 1488, y: 2480 },
        image: "",
        lore: "More information about Gadros Ruins is coming soon.",
        information: "",
        bonus: "",
        npcs: [],
        links: [],
      },
    },
    {
      name: "Shadow Forest", // Seemed like it needed a name, might have a different name.
      fontSize: 20,
      region: "Darkwoods", 
      details: {
        title: "Shadow Forest",
        coordinates: { x: 1462, y: 2709 },
        image: "",
        lore: "More information about Shadow Forest is coming soon.",
        information: "",
        bonus: "",
        npcs: [],
        links: [],
      },
    },
    {
      name: "Termigon Mound", // Changed the name from Termigon Hive to Termigon Mound, seems more fitting.
      fontSize: 20,
      region: "Darkwoods", // Changed the name from Termigon Hive to Termigon Mound, seems more fitting. Question Mark
      details: {
        title: "Termigon Mound",
        coordinates: { x: 676, y: 3519 },
        image: "",
        lore: "More information about Termigon Mound is coming soon.",
        information: "",
        bonus: "",
        npcs: [],
        links: [],
      },
    },

    // Battle Plains Places of Interest
    {
      name: "Wasp Hive",
      fontSize: 20,
      region: "Battle Plains",
      details: {
        title: "Wasp Hive",
        coordinates: { x: 1656, y: 2958 },
        image: "",
        lore: "More information about Wasp Hive is coming soon.",
        information: "",
        bonus: "",
        npcs: [],
        links: [],
      },
    },

    // Black Swamp Places of Interest
    {
      name: "Drakkan",
      fontSize: 20,
      region: "Black Swamp",
      details: {
        title: "Drakkan",
        coordinates: { x: 2805, y: 3806 },
        image: "",
        lore: "More information about Drakkan is coming soon.",
        information: "",
        bonus: "",
        npcs: [],
        links: [],
      },
    },
    {
      name: "Kobold Camp",
      fontSize: 20,
      region: "Black Swamp",
      details: {
        title: "Kobold Camp",
        coordinates: { x: 3247, y: 3817 },
        image: "",
        lore: "More information about Kobold Camp is coming soon.",
        information: "",
        bonus: "",
        npcs: [],
        links: [],
      },
    },
    {
      name: "Medosk Mountain Pass",
      fontSize: 20,
      region: "Black Swamp",
      details: {
        title: "Medosk Mountain Pass",
        coordinates: { x: 3230, y: 3775 },
        image: "",
        lore: "More information about Medosk Mountain Pass is coming soon.",
        information: "",
        bonus: "",
        npcs: [],
        links: [],
      },
    },
    {
      name: "Kobold Village",
      fontSize: 20,
      region: "Black Swamp",
      details: {
        title: "Kobold Village",
        coordinates: { x: 2832, y: 3924 },
        image: "",
        lore: "More information about Kobold Village is coming soon.",
        information: "",
        bonus: "",
        npcs: [],
        links: [],
      },
    },
    {
      name: "Temple of Agon",
      fontSize: 20,
      region: "Black Swamp",
      details: {
        title: "Temple of Agon",
        coordinates: { x: 3114, y: 3634 },
        image: "",
        lore: "More information about Temple of Agon is coming soon.",
        information: "",
        bonus: "",
        npcs: [],
        links: [],
      },
    },
    {
      name: "Scorpion Pit",
      fontSize: 20,
      region: "Black Swamp",
      details: {
        title: "Scorpion Pit",
        coordinates: { x: 3130, y: 3656 },
        image: "",
        lore: "More information about Scorpion Pit is coming soon.",
        information: "",
        bonus: "",
        npcs: [],
        links: [],
      },
    },
    {
      name: "Sogrun Mine",
      fontSize: 20,
      region: "Black Swamp",
      details: {
        title: "Sogrun Mine",
        coordinates: { x: 3153, y: 3733 },
        image: "",
        lore: "More information about Sogrun Mine is coming soon.",
        information: "",
        bonus: "",
        npcs: [],
        links: [],
      },
    },
    {
      name: "Old Ale Warehouse\n(Closed)",
      fontSize: 20,
      region: "Black Swamp",
      details: {
        title: "Old Ale Warehouse\n(Closed)",
        coordinates: { x: 2816, y: 3260 },
        image: "",
        lore: "More information about Old Ale Warehouse\n(Closed) is coming soon.",
        information: "",
        bonus: "",
        npcs: [],
        links: [],
      },
    },
    {
      name: "Valekar's Fortress",
      fontSize: 20,
      region: "Black Swamp",
      details: {
        title: "Valekar's Fortress",
        coordinates: { x: 3100, y: 3487 },
        image: "",
        lore: "More information about Valekar's Fortress is coming soon.",
        information: "",
        bonus: "",
        npcs: [],
        links: [],
      },
    },

    // Highlands Places of Interest
    {
      name: "Emporium Abbey",
      fontSize: 20,
      region: "Highlands",
      details: {
        title: "Emporium Abbey",
        coordinates: { x: 2768, y: 3165 },
        image: "",
        lore: "More information about Emporium Abbey is coming soon.",
        information: "",
        bonus: "",
        npcs: [],
        links: [],
      },
    },
    {
      name: "Ancient Site of Minos",
      fontSize: 20,
      region: "Highlands",
      details: {
        title: "Ancient Site of Minos",
        coordinates: { x: 2929, y: 3168 },
        image: "",
        lore: "More information about Ancient Site of Minos is coming soon.",
        information: "",
        bonus: "",
        npcs: [],
        links: [],
      },
    },
    {
      name: "Minotaur Maze",
      fontSize: 20,
      region: "Highlands",
      details: {
        title: "Minotaur Maze",
        coordinates: { x: 3000, y: 3039 },
        image: "",
        lore: "More information about Minotaur Maze is coming soon.",
        information: "",
        bonus: "",
        npcs: [],
        links: [],
      },
    },
    {
      name: "Thief Fort",
      fontSize: 20,
      region: "Highlands",
      details: {
        title: "Thief Fort",
        coordinates: { x: 3176, y: 3068 },
        image: "",
        lore: "More information about Thief Fort is coming soon.",
        information: "",
        bonus: "",
        npcs: [],
        links: [],
      },
    },
    {
      name: "Supply Shelter",
      fontSize: 20,
      region: "Highlands",
      details: {
        title: "Supply Shelter",
        coordinates: { x: 3367, y: 2957 },
        image: "",
        lore: "More information about Supply Shelter is coming soon.",
        information: "",
        bonus: "",
        npcs: [],
        links: [],
      },
    },
    {
      name: "Third Book Temple",
      fontSize: 20,
      region: "Highlands",
      details: {
        title: "Third Book Temple",
        coordinates: { x: 2983, y: 2700 },
        image: "",
        lore: "More information about Third Book Temple is coming soon.",
        information: "",
        bonus: "",
        npcs: [],
        links: [],
      },
    },
    {
      name: "Horibus's Camp",
      fontSize: 20,
      region: "Highlands",
      details: {
        title: "Horibus's Camp",
        coordinates: { x: 3467, y: 2642 },
        image: "",
        lore: "More information about Horibus's Camp is coming soon.",
        information: "",
        bonus: "",
        npcs: [],
        links: [],
      },
    },
    {
      name: "Cave\n(NO ENTRY)",
      fontSize: 20,
      region: "Highlands",
      details: {
        title: "Cave\n(NO ENTRY)",
        coordinates: { x: 3561, y: 1923 },
        image: "",
        lore: "More information about Cave\n(NO ENTRY) is coming soon.",
        information: "",
        bonus: "",
        npcs: [],
        links: [],
      },
    },
    {
      name: "Ethera Mining Company",
      fontSize: 20,
      region: "Highlands",
      details: {
        title: "Ethera Mining Company",
        coordinates: { x: 3609, y: 3620 },
        image: "",
        lore: "More information about Ethera Mining Company is coming soon.",
        information: "",
        bonus: "",
        npcs: [],
        links: [],
      },
    },
    {
      name: "Warg Pen",
      fontSize: 20,
      region: "Highlands",
      details: {
        title: "Warg Pen",
        coordinates: { x: 3335, y: 3733 },
        image: "",
        lore: "More information about Warg Pen is coming soon.",
        information: "",
        bonus: "",
        npcs: [],
        links: [],
      },
    },

    // Valley of Giants Places of Interest

    // Heartwood Coast Places of Interest
    {
      name: "Infiltrator Camp",
      fontSize: 20,
      region: "Heartwood Coast",
      details: {
        title: "Infiltrator Camp",
        coordinates: { x: 2471, y: 1505 },
        image: "",
        lore: "More information about Infiltrator Camp is coming soon.",
        information: "",
        bonus: "",
        npcs: [],
        links: [],
      },
    },
    {
      name: "Gnobol Manor",
      fontSize: 20,
      region: "Heartwood Coast",
      details: {
        title: "Gnobol Manor",
        coordinates: { x: 3095, y: 1474 },
        image: "",
        lore: "More information about Gnobol Manor is coming soon.",
        information: "",
        bonus: "",
        npcs: [],
        links: [],
      },
    },
    {
      name: "Gnobol Mauseleum",
      fontSize: 20,
      region: "Heartwood Coast",
      details: {
        title: "Gnobol Mauseleum",
        coordinates: { x: 3095, y: 1568 },
        image: "",
        lore: "More information about Gnobol Mauseleum is coming soon.",
        information: "",
        bonus: "",
        npcs: [],
        links: [],
      },
    },
    {
      name: "Hunter's Lodge",
      fontSize: 20,
      region: "Heartwood Coast",
      details: {
        title: "Hunter's Lodge",
        coordinates: { x: 2938, y: 1844 },
        image: "",
        lore: "More information about Hunter's Lodge is coming soon.",
        information: "",
        bonus: "",
        npcs: [],
        links: [],
      },
    },
    {
      name: "Talazarian Fort",
      fontSize: 20,
      region: "Heartwood Coast",
      details: {
        title: "Talazarian Fort",
        coordinates: { x: 2918, y: 2256 },
        image: "",
        lore: "More information about Talazarian Fort is coming soon.",
        information: "",
        bonus: "",
        npcs: [],
        links: [],
      },
    },
    {
      name: "Temple of Kuthos",
      fontSize: 20,
      region: "Heartwood Coast",
      details: {
        title: "Temple of Kuthos",
        coordinates: { x: 2758, y: 2396 },
        image: "",
        lore: "More information about Temple of Kuthos is coming soon.",
        information: "",
        bonus: "",
        npcs: [],
        links: [],
      },
    },

    // Tundria Places of Interest
    {
      name: "Orc Raider Camp",
      fontSize: 20,
      region: "Tundria",
      details: {
        title: "Orc Raider Camp",
        coordinates: { x: 2944, y: 1223 },
        image: "",
        lore: "More information about Orc Raider Camp is coming soon.",
        information: "",
        bonus: "",
        npcs: [],
        links: [],
      },
    },
    {
      name: "Elsinea Manor",
      fontSize: 20,
      region: "Tundria",
      details: {
        title: "Elsinea Manor",
        coordinates: { x: 2615, y: 1248 },
        image: "",
        lore: "More information about Elsinea Manor is coming soon.",
        information: "",
        bonus: "",
        npcs: [],
        links: [],
      },
    },
    {
      name: "Frost Troll Coast",
      fontSize: 20,
      region: "Tundria",
      details: {
        title: "Frost Troll Coast",
        coordinates: { x: 2574, y: 1128 },
        image: "",
        lore: "More information about Frost Troll Coast is coming soon.",
        information: "",
        bonus: "",
        npcs: [],
        links: [],
      },
    },
    {
      name: "Trapper Grayth's Dwelling",
      fontSize: 20,
      region: "Tundria",
      details: {
        title: "Trapper Grayth's Dwelling",
        coordinates: { x: 3399, y: 818 },
        image: "",
        lore: "More information about Trapper Grayth's Dwelling is coming soon.",
        information: "",
        bonus: "",
        npcs: [],
        links: [],
      },
    },
    {
      name: "Infiltrator Camp",
      fontSize: 20,
      region: "Tundria",
      details: {
        title: "Infiltrator Camp",
        coordinates: { x: 3607, y: 1038 },
        image: "",
        lore: "More information about Infiltrator Camp is coming soon.",
        information: "",
        bonus: "",
        npcs: [],
        links: [],
      },
    },
    {
      name: "Altargrade",
      fontSize: 20,
      region: "Tundria",
      details: {
        title: "Altargrade",
        coordinates: { x: 3238, y: 754 },
        image: "",
        lore: "More information about Altargrade is coming soon.",
        information: "",
        bonus: "",
        npcs: [],
        links: [],
      },
    },
    {
      name: "Orc Raider Fort",
      fontSize: 20,
      region: "Tundria",
      details: {
        title: "Orc Raider Fort",
        coordinates: { x: 3110, y: 860 },
        image: "",
        lore: "More information about Orc Raider Fort is coming soon.",
        information: "",
        bonus: "",
        npcs: [],
        links: [],
      },
    },
    {
      name: "Hammerfist Mine Camp",
      fontSize: 20,
      region: "Tundria",
      details: {
        title: "Hammerfist Mine Camp",
        coordinates: { x: 2761, y: 614 },
        image: "",
        lore: "More information about Hammerfist Mine Base Camp is coming soon.",
        information: "",
        bonus: "",
        npcs: [],
        links: [],
      },
    },
    {
      name: "Stormholde",
      fontSize: 20,
      region: "Tundria",
      details: {
        title: "Stormholde",
        coordinates: { x: 2562, y: 928 },
        image: "",
        lore: "More information about Stormholde is coming soon.",
        information: "",
        bonus: "",
        npcs: [],
        links: [],
      },
    },
    {
      name: "Ruins of Osgarl",
      fontSize: 20,
      region: "Tundria",
      details: {
        title: "Ruins of Osgarl",
        coordinates: { x: 2542, y: 413 },
        image: "",
        lore: "More information about Ruins of Osgarl is coming soon.",
        information: "",
        bonus: "",
        npcs: [],
        links: [],
      },
    },
    {
      name: "Castle of Artraxis",
      fontSize: 20,
      region: "Tundria",
      details: {
        title: "Castle of Artraxis",
        coordinates: { x: 2878, y: 412 },
        image: "",
        lore: "More information about Castle of Artraxis is coming soon.",
        information: "",
        bonus: "",
        npcs: [],
        links: [],
      },
    },

    // Breakwater Places of Interest
    // New Royale Island Places of Interest
    {
      name: "Pirate Raider's Camp",
      fontSize: 20,
      region: "Breakwater",
      details: {
        title: "Pirate Raider's Camp",
        coordinates: { x: 1350, y: 1761 },
        image: "",
        lore: "More information about Pirate Raider's Camp is coming soon.",
        information: "",
        bonus: "",
        npcs: [],
        links: [],
      },
    },
    {
      name: "Athropiniax's Temple",
      fontSize: 20,
      region: "Breakwater",
      details: {
        title: "Athropiniax's Temple",
        coordinates: { x: 1783, y: 2430 },
        image: "",
        lore: "More information about Athropiniax's Temple is coming soon.",
        information: "",
        bonus: "",
        npcs: [],
        links: [],
      },
    },

    // New Town Island Places of Interest
    {
      name: "Undead Dwarven Fort",
      fontSize: 20,
      region: "Breakwater",
      details: {
        title: "Undead Dwarven Fort",
        coordinates: { x: 1923, y: 1731 },
        image: "",
        lore: "More information about Undead Dwarven Fort is coming soon.",
        information: "",
        bonus: "",
        npcs: [],
        links: [],
      },
    },
    {
      name: "Deadwing's Lair",
      fontSize: 20,
      region: "Breakwater",
      details: {
        title: "Deadwing's Lair",
        coordinates: { x: 1944, y: 1691 },
        image: "",
        lore: "More information about Deadwing's Lair is coming soon.",
        information: "",
        bonus: "",
        npcs: [],
        links: [],
      },
    },
    {
      name: "Dwarf Fortress",
      fontSize: 20,
      region: "Breakwater",
      details: {
        title: "Dwarf Fortress",
        coordinates: { x: 2172, y: 1509 },
        image: "",
        lore: "More information about Dwarf Fortress is coming soon.",
        information: "",
        bonus: "",
        npcs: [],
        links: [],
      },
    },

    // Roycroft Island Places of Interest
    {
      name: "Sea Pirate Shack",
      fontSize: 20,
      region: "Breakwater",
      details: {
        title: "Sea Pirate Shack",
        coordinates: { x: 2214, y: 2252 },
        image: "",
        lore: "More information about Sea Pirate Shack is coming soon.",
        information: "",
        bonus: "",
        npcs: [],
        links: [],
      },
    },

    // Places of Interest - Region: Western Isles
    {
      name: "Talazar's Castle",
      fontSize: 25,
      region: "Western Isles",
      details: {
        title: "Talazar's Castle",
        coordinates: { x: 1103, y: 3291 },
        image: "",
        lore: "More information about Talazar's Castle is coming soon.",
        information: "",
        bonus: "",
        npcs: [],
        links: [],
      },
    },

    // Places of Interest - Region: Broken Figer

    // Places of Interest - Region: Sands of Creation
    // Places of Interest - Ruhura 
    {
      name: "Ruhura Outpost",
      fontSize: 20,
      region: "Sands of Creation",
      details: {
        title: "Ruhura Outpost",
        coordinates: { x: 942, y: 3986 },
        image: "",
        lore: "More information about Ruhura Outpost is coming soon.",
        information: "",
        bonus: "",
        npcs: [],
        links: [],
      },
    },
    {
      name: "Sand Golem Crypt",
      fontSize: 20,
      region: "Sands of Creation",
      details: {
        title: "Sand Golem Crypt",
        coordinates: { x: 841, y: 3923 },
        image: "",
        lore: "More information about Sand Golem Crypt is coming soon.",
        information: "",
        bonus: "",
        npcs: [],
        links: [],
      },
    },
    {
      name: "Lupinsix's Lair",
      fontSize: 20,
      region: "Sands of Creation",
      details: {
        title: "Lupinsix's Lair",
        coordinates: { x: 792, y: 3837 },
        image: "",
        lore: "More information about Lupinsix's Lair is coming soon.",
        information: "",
        bonus: "",
        npcs: [],
        links: [],
      },
    },
    {
      name: "Tomna's House",
      fontSize: 20,
      region: "Sands of Creation",
      details: {
        title: "Tomna's House",
        coordinates: { x: 719, y: 3681 },
        image: "",
        lore: "More information about Tomna's House is coming soon.",
        information: "",
        bonus: "",
        npcs: [],
        links: [],
      },
    },
    {
      name: "Artonian Fort",
      fontSize: 20,
      region: "Sands of Creation",
      details: {
        title: "Artonian Fort",
        coordinates: { x: 555, y: 3667 },
        image: "",
        lore: "More information about Artonian Fort is coming soon.",
        information: "",
        bonus: "",
        npcs: [],
        links: [],
      },
    },
    {
      name: "Artonian Cave",
      fontSize: 20,
      region: "Sands of Creation",
      details: {
        title: "Artonian Cave",
        coordinates: { x: 489, y: 3651 },
        image: "",
        lore: "More information about Artonian Cave is coming soon.",
        information: "",
        bonus: "",
        npcs: [],
        links: [],
      },
    },
    {
      name: "The GateKeeper",
      fontSize: 20,
      region: "Sands of Creation",
      details: {
        title: "The GateKeeper",
        coordinates: { x: 421, y: 3685 },
        image: "",
        lore: "More information about The GateKeeper is coming soon.",
        information: "",
        bonus: "",
        npcs: [],
        links: [],
      },
    },
    {
      name: "Dragon Lair",
      fontSize: 20,
      region: "Sands of Creation",
      details: {
        title: "Dragon Lair",
        coordinates: { x: 113, y: 3468 },
        image: "",
        lore: "More information about Dragon Lair is coming soon.",
        information: "",
        bonus: "",
        npcs: [],
        links: [],
      },
    },
    // Done

    // Khafra
    {
      name: "Khafra Fishing Outpost",
      fontSize: 20,
      region: "Sands of Creation",
      details: {
        title: "Khafra Fishing Outpost",
        coordinates: { x: 87, y: 2725 },
        image: "",
        lore: "More information about Khafra Fishing Outpost is coming soon.",
        information: "",
        bonus: "",
        npcs: [],
        links: [],
      },
    },
    {
      name: "Baniti's Family Crypt",
      fontSize: 20,
      region: "Sands of Creation",
      details: {
        title: "Baniti's Family Crypt",
        coordinates: { x: 312, y: 2978 },
        image: "",
        lore: "More information about Baniti's Family Crypt is coming soon.",
        information: "",
        bonus: "",
        npcs: [],
        links: [],
      },
    },
    {
      name: "Blacktail's Crypt",
      fontSize: 20,
      region: "Sands of Creation",
      details: {
        title: "Blacktail's Crypt",
        coordinates: { x: 55, y: 3025 },
        image: "",
        lore: "More information about Blacktail's Crypt is coming soon.",
        information: "",
        bonus: "",
        npcs: [],
        links: [],
      },
    },
    {
      name: "The Guardian",
      fontSize: 20,
      region: "Sands of Creation",
      details: {
        title: "The Guardian",
        coordinates: { x: 168, y: 3157 },
        image: "",
        lore: "More information about The Guardian is coming soon.",
        information: "",
        bonus: "",
        npcs: [],
        links: [],
      },
    },
    {
      name: "Undead Artonian Crypt",
      fontSize: 20,
      region: "Sands of Creation",
      details: {
        title: "Undead Artonian Crypt",
        coordinates: { x: 262, y: 3249 },
        image: "",
        lore: "More information about Undead Artonian Crypt is coming soon.",
        information: "",
        bonus: "",
        npcs: [],
        links: [],
      },
    },
    {
      name: "Ancient Artonian Swordsman Dungeon",
      fontSize: 20,
      region: "Sands of Creation",
      details: {
        title: "Ancient Artonian Swordsman Dungeon",
        coordinates: { x: 141, y: 3328 },
        image: "",
        lore: "More information about Ancient Artonian Swordsman Dungeon is coming soon.",
        information: "",
        bonus: "",
        npcs: [],
        links: [],
      },
    },
    // Done
  ],

  waterBodies: [
    //Valinor Island Water Bodies
    {
      name: "Gut Rot Swamp",
      fontSize: 20,
      region: "Valinor",
      details: {
        title: "Gut Rot Swamp",
        coordinates: { x: 1176, y: 412 },
        image: "",
        lore: "More information about Gut Rot Swamp is coming soon.",
        information: "",
        bonus: "",
        npcs: [],
        links: [],
      },
    },

    // Krythan Island Water Bodies

    // Silvest Valley Region Water Bodies
    {
      name: "Lake Silvest",
      fontSize: 20,
      region: "Krythan",
      details: {
        title: "Lake Silvest",
        coordinates: { x: 1266, y: 1219 },
        image: "",
        lore: "More information about Lake Silvest is coming soon.",
        information: "",
        bonus: "",
        npcs: [],
        links: [],
      },
    },
    {
      name: "Chokecherry Pond",
      fontSize: 20,
      region: "Krythan",
      details: {
        title: "Chokecherry Pond",
        coordinates: { x: 1039, y: 1217 },
        image: "",
        lore: "More information about Chokecherry Pond is coming soon.",
        information: "",
        bonus: "",
        npcs: [],
        links: [],
      },
    },

    // Bodies of Water - Region: Krythan
    {
      name: "Queen's Lake",
      fontSize: 25,
      region: "Krythan",
      details: {
        title: "Queen's Lake",
        coordinates: { x: 389, y: 1089 },
        image: "",
        lore: "More information about Queen's Lake is coming soon.",
        information: "",
        bonus: "",
        npcs: [],
        links: [],
      },
    },
    {
      name: "Crow Lake",
      fontSize: 20,
      region: "Krythan",
      details: {
        title: "Crow Lake",
        coordinates: { x: 848, y: 1155 },
        image: "",
        lore: "More information about Crow Lake is coming soon.",
        information: "",
        bonus: "",
        npcs: [],
        links: [],
      },
    },
    {
      name: "Krythan Swamp",
      fontSize: 20,
      region: "Krythan",
      details: {
        title: "Krythan Swamp",
        coordinates: { x: 189, y: 1765 },
        image: "",
        lore: "More information about Krythan Swamp is coming soon.",
        information: "",
        bonus: "",
        npcs: [],
        links: [],
      },
    },

    /* Mainland Water Bodies */
    // Bodies of Water - Region: Darkwoods
    {
      name: "Cairn Lake",
      fontSize: 20,
      region: "Darkwoods",
      details: {
        title: "Cairn Lake",
        coordinates: { x: 1014, y: 2868 },
        image: "",
        lore: "More information about Cairn Lake is coming soon.",
        information: "",
        bonus: "",
        npcs: [],
        links: [],
      },
    },
    {
      name: "Lake Mraya",
      fontSize: 20,
      region: "Darkwoods",
      details: {
        title: "Lake Mraya",
        coordinates: { x: 777, y: 2987 },
        image: "",
        lore: "More information about Lake Mraya is coming soon.",
        information: "",
        bonus: "",
        npcs: [],
        links: [],
      },
    },
    {
      name: "Josody Swamp",
      fontSize: 18,
      region: "Darkwoods",
      details: {
        title: "Josody Swamp",
        coordinates: { x: 1128, y: 2675 },
        image: "",
        lore: "More information about Josody Swamp is coming soon.",
        information: "",
        bonus: "",
        npcs: [],
        links: [],
      },
    },
    {
      name: "Greenteeth Swamp", // Not sure about the name, just thought it needed one.
      fontSize: 20,
      region: "Darkwoods", 
      details: {
        title: "Greenteeth Swamp",
        coordinates: { x: 1639, y: 2599 },
        image: "",
        lore: "More information about Greenteeth Swamp is coming soon.",
        information: "",
        bonus: "",
        npcs: [],
        links: [],
      },
    },
    {
      name: "Darkfell Marsh",
      fontSize: 20,
      region: "Darkwoods",
      details: {
        title: "Darkfell Marsh",
        coordinates: { x: 1010, y: 3091 },
        image: "",
        lore: "More information about Darkfell Marsh is coming soon.",
        information: "",
        bonus: "",
        npcs: [],
        links: [],
      },
    },

    // Bodies of Water - Region: Battle Plains
    {
      name: "Proudblood Sound",
      fontSize: 20,
      region: "Battle Plains",
      details: {
        title: "Proudblood Sound",
        coordinates: { x: 2271, y: 3769 },
        image: "",
        lore: "More information about Proudblood Sound is coming soon.",
        information: "",
        bonus: "",
        npcs: [],
        links: [],
      },
    },
    {
      name: "Chlera Bay",
      fontSize: 30,
      region: "Battle Plains",
      details: {
        title: "Chlera Bay",
        coordinates: { x: 2557, y: 3712 },
        image: "",
        lore: "More information about Chlera Bay is coming soon.",
        information: "",
        bonus: "",
        npcs: [],
        links: [],
      },
    },

    // Bodies of Water - Region: Battle Plains
    // There are many bodies of water in the Battle Plains, but none have specific names. I'm going to add a few especially around whirlpool portals.

    // Bodies of Water - Region: Black Swamp
    {
      name: "Vorda Swamp",
      fontSize: 20,
      region: "Black Swamp",
      details: {
        title: "Vorda Swamp",
        coordinates: { x: 2786, y: 3681 },
        image: "",
        lore: "More information about Vorda Swamp is coming soon.",
        information: "",
        bonus: "",
        npcs: [],
        links: [],
      },
    },
    {
      name: "Canis Lake",
      fontSize: 20,
      region: "Black Swamp",
      details: {
        title: "Canis Lake",
        coordinates: { x: 2829, y: 3508 },
        image: "",
        lore: "More information about Canis Lake is coming soon.",
        information: "",
        bonus: "",
        npcs: [],
        links: [],
      },
    },
    {
      name: "Lake Dresta",
      fontSize: 20,
      region: "Black Swamp",
      details: {
        title: "Lake Dresta",
        coordinates: { x: 2918, y: 3649 },
        image: "",
        lore: "More information about Lake Dresta is coming soon.",
        information: "",
        bonus: "",
        npcs: [],
        links: [],
      },
    },
    {
      name: "Key Marsh",
      fontSize: 20,
      region: "Black Swamp",
      details: {
        title: "Key Marsh",
        coordinates: { x: 3398, y: 3923 },
        image: "",
        lore: "More information about Key Marsh is coming soon.",
        information: "",
        bonus: "",
        npcs: [],
        links: [],
      },
    },

    // Bodies of Water - Region: Highlands
    {
      name: "West Lake",
      fontSize: 20,
      region: "Highlands",
      details: {
        title: "West Lake",
        coordinates: { x: 3376, y: 2979 },
        image: "",
        lore: "More information about West Lake is coming soon.",
        information: "",
        bonus: "",
        npcs: [],
        links: [],
      },
    },
    {
      name: "Parian Lake",
      fontSize: 20,
      region: "Highlands",
      details: {
        title: "Parian Lake",
        coordinates: { x: 3511, y: 2950 },
        image: "",
        lore: "More information about Parian Lake is coming soon.",
        information: "",
        bonus: "",
        npcs: [],
        links: [],
      },
    },
    {
      name: "Town Lake",
      fontSize: 20,
      region: "Highlands",
      details: {
        title: "Town Lake",
        coordinates: { x: 3586, y: 3114 },
        image: "",
        lore: "More information about Town Lake is coming soon.",
        information: "",
        bonus: "",
        npcs: [],
        links: [],
      },
    },
    {
      name: "Kor's Lake",
      fontSize: 20,
      region: "Highlands",
      details: {
        title: "Kor's Lake",
        coordinates: { x: 3575, y: 3233 },
        image: "",
        lore: "More information about Kor's Lake is coming soon.",
        information: "",
        bonus: "",
        npcs: [],
        links: [],
      },
    },
    {
      name: "Lake Ulthien",
      fontSize: 25,
      region: "Highlands",
      details: {
        title: "Lake Ulthien",
        coordinates: { x: 3032, y: 3228 },
        image: "",
        lore: "More information about Lake Ulthien is coming soon.",
        information: "",
        bonus: "",
        npcs: [],
        links: [],
      },
    },
    {
      name: "Glutton Lake",
      fontSize: 25,
      region: "Highlands",
      details: {
        title: "Glutton Lake",
        coordinates: { x: 3460, y: 2701 },
        image: "",
        lore: "More information about Glutton Lake is coming soon.",
        information: "",
        bonus: "",
        npcs: [],
        links: [],
      },
    },
    {
      name: "Lake Kallon",
      alias: "Arda Pond", // Added an alias for a quest that calls it Arda Pond.
      fontSize: 20,
      region: "Highlands",
      details: {
        title: "Lake Kallon",
        coordinates: { x: 3545, y: 3411 },
        image: "",
        lore: "More information about Lake Kallon is coming soon.",
        information: "",
        bonus: "",
        npcs: [],
        links: [],
      },
    },
    {
      name: "Orc Pond",
      fontSize: 20,
      region: "Highlands",
      details: {
        title: "Orc Pond",
        coordinates: { x: 3182, y: 3600 },
        image: "",
        lore: "More information about Orc Pond is coming soon.",
        information: "",
        bonus: "",
        npcs: [],
        links: [],
      },
    },

    // Bodies of Water - Region: Valley of Giants
    {
      name: "Greenmead Lake",
      fontSize: 20,
      region: "Valley of Giants",
      details: {
        title: "Greenmead Lake",
        coordinates: { x: 3111, y: 2843 },
        image: "",
        lore: "More information about Greenmead Lake is coming soon.",
        information: "",
        bonus: "",
        npcs: [],
        links: [],
      },
    },

    // Bodies of Water - Region: Heartwood Coast

    // Bodies of Water - Region: Tundria

    // Bodies of Water - Region: Breakwater
    // New Royale
    // New Town
    // Roycroft
    {
      name: "The Choke",
      fontSize: 20,
      region: "Breakwater",
      details: {
        title: "The Choke",
        coordinates: { x: 2269, y: 2176 },
        image: "",
        lore: "More information about The Choke is coming soon.",
        information: "",
        bonus: "",
        npcs: [],
        links: [],
      },
    },

    // Bodies of Water - Region: Western Isles

    // Bodies of Water - Region: Broken Finger
    {
      name: "Broken Lake",
      fontSize: 20,
      region: "Broken Finger",
      details: {
        title: "Broken Lake",
        coordinates: { x: 1447, y: 3752 },
        image: "",
        lore: "More information about Broken Lake is coming soon.",
        information: "",
        bonus: "",
        npcs: [],
        links: [],
      },
    },
    {
      name: "Obsidian Lake",
      fontSize: 25,
      region: "Broken Finger",
      details: {
        title: "Obsidian Lake",
        coordinates: { x: 1353, y: 3512 },
        image: "",
        lore: "More information about Obsidian Lake is coming soon.",
        information: "",
        bonus: "",
        npcs: [],
        links: [],
      },
    },

    // Bodies of Water - Region: Sands of Creation
    // Ruhura
    // Khafra
    {
      name: "Khafra Oasis",
      fontSize: 20,
      region: "Sands of Creation",
      details: {
        title: "Khafra Oasis",
        coordinates: { x: 217, y: 3015 },
        image: "",
        lore: "More information about Khafra Oasis is coming soon.",
        information: "",
        bonus: "",
        npcs: [],
        links: [],
      },
    },
    {
      name: "Chomper's Oasis",
      fontSize: 20,
      region: "Sands of Creation",
      details: {
        title: "Chomper's Oasis",
        coordinates: { x: 90, y: 3266 },
        image: "",
        lore: "More information about Chomper's Oasis is coming soon.",
        information: "",
        bonus: "",
        npcs: [],
        links: [],
      },
    },
  ],

  mountains: [
    // I added Regions to the mountain ranges but some of them span multiple regions so I just picked one region for each mountain range. Might need to change later.
    // Mountains - Region: Valinor

    // Mountains - Region: Krythan

    // Mountains - Region: Darkwoods

    // Mountains - Region: Battle Plains

    // Mountains - Region: Black Swamp
    {
      name: "Medosk Mountains",
      fontSize: 20,
      region: "Black Swamp",
      details: {
        title: "Medosk Mountains",
        coordinates: [
          { x: 2980, y: 3532 },
          { x: 3150, y: 3846 }, // Added more coordinates to better represent the range
          { x: 3482, y: 3653 },
          { x: 3764, y: 3416 },
        ],
        image: "",
        lore: "More information about Medosk Mountains is coming soon.",
        information: "",
        bonus: "",
        npcs: [],
        links: [],
      },
    },

    // Mountains - Region: Highlands
    {
      name: "Eastern Mountains",
      fontSize: 20,
      region: "Highlands",
      details: {
        title: "Eastern Mountains",
        coordinates: [
          { x: 3134, y: 2570 },
          { x: 3530, y: 2878 },
          { x: 3241, y: 2062 }, // Added a second coordinate for the same label
          { x: 3482, y: 1765 },
          { x: 3693, y: 3075 },
        ],
        image: "",
        lore: "More information about Eastern Mountains is coming soon.",
        information: "",
        bonus: "",
        npcs: [],
        links: [],
      },
    },

    // Mountains - Region: Valley of Giants

    // Mountains - Region: Heartwood Coast

    // Mountains - Region: Tundria

    // Mountains - Region: Breakwater

    // Mountains - Region: Western Isles

    // Mountains - Region: Broken Finger
    
  ],
};
